development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_dev
  pool: 5
  username: newuser1
  password: 123456
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_test
  pool: 5
  username: newuser1
  password: 123456
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_production
  pool: 5
  username: newuser1
  password: 123456